------ADMIN-----
CREATE TABLE LMS_ADMIN(MANAGER_ID NUMBER PRIMARY KEY,MANAGER_NAME VARCHAR2(50),MANAGER_EMAIL VARCHAR2(70),MANAGER_PASSWORD VARCHAR2(40));
DESC LMS_ADMIN;
INSERT INTO  LMS_ADMIN VALUES(101,'POTHIRAJ','POTHI@GMAIL.COM','POTHIRAJ97');
SELECT * FROM LMS_ADMIN;

-----EMPLOYEE TABLE-----
CREATE TABLE LMS_EMPLOYEE(EMP_ID NUMBER GENERATED  ALWAYS AS IDENTITY START WITH 2930,EMP_NAME VARCHAR2(40), EMP_DEPARTMENT VARCHAR2(40),EMP_EMAIL VARCHAR2(50),EMP_PASSWORD VARCHAR2(50),
CONSTRAINT PK_EMP_ID  PRIMARY KEY(EMP_ID));
DESC LMS_EMPLOYEE;
SELECT * FROM LMS_EMPLOYEE;

------drop table LMS_EMPLOYEE;

------leave request-------

CREATE TABLE LEAVE_RES(REQUEST_ID NUMBER  GENERATED  ALWAYS AS IDENTITY START WITH 100 ,EMP_ID NUMBER,REASON VARCHAR2(50),FROM_DATE DATE,TO_DATE DATE,
NO_OFDAYS NUMBER,STATUS VARCHAR2(40)DEFAULT 'PROCESSING',CONSTRAINT PK_REQUEST_ID  PRIMARY KEY(REQUEST_ID),
FOREIGN KEY( EMP_ID) REFERENCES LMS_EMPLOYEE(EMP_ID));
DESC LEAVE_RES;
SELECT*FROM LEAVE_RES;
commit;


-----leave status------

CREATE TABLE LEV_STATUS(MANAGER_ID NUMBER ,REQUEST_ID NUMBER,EMP_ID NUMBER ,STATUS VARCHAR2(30) DEFAULT 'PROCESSING',
FOREIGN KEY (REQUEST_ID)REFERENCES LEAVE_RES(REQUEST_ID));
DESC LEV_STATUS;
SELECT manager_id,request_id,status FROM LEV_STATUS;
SELECT *FROM LEV_STATUS;

INSERT into lev_status(manager_id,emp_id,request_id) values(101,4444,100);
commit;

------leave balance------

CREATE TABLE LEAVE_BAL(EMP_ID NUMBER,CAUSAL_LEV NUMBER DEFAULT 10,MEDICAL_LEV NUMBER DEFAULT 10,CAUSAL_LEV_BAL NUMBER DEFAULT 10,MEDI_LEV_BAL NUMBER DEFAULT 10,PAID_LEV NUMBER DEFAULT 0,
FOREIGN KEY (EMP_ID) REFERENCES LMS_EMPLOYEE (EMP_ID));
DESC LEAVE_BAL;
SELECT* FROM LEAVE_BAL;









--drop table LEAVE_BAL;
desc leave_bal;
select * from LEAVE_BAL where emp_id=6297;
commit;
insert into leave_bal(emp_id,causal_lev_bal,medi_lev_bal,paid_lev) values (4444,1,0,0);
delete from leave_bal;
update leave_bal set causal_lev_bal=(SELECT causal_lev_bal from leave_bal where emp_id=4444 )+3 where emp_id=4444;

SELECT causal_lev_bal from leave_bal where emp_id=4444;
delete from leave_bal where causal_lev_bal=1;

drop table lms_employee;
drop table leave_res;
drop table leave_bal;
